#!/usr/bin/env python3
# Group Members: Ananthajit ("Ananth") Srikanth (asrikan1), Layla Myers (laamyers), Teresa Joseph (tkjoseph)
# Required modules: sys

ITS1Seqs = ['CTTGGTCATTTAGAGGAAGTAA', 'CTCGGTCATTTAGAGGAAGTAA', 'CTTGGTCATTTAGAGGAACTAA',
            'CCCGGTCATTTAGAGGAAGTAA', 'CTAGGCTATTTAGAGGAAGTAA', 'CTTAGTTATTTAGAGGAAGTAA',
            'CTACGTCATTTAGAGGAAGTAA', 'CTTGGTCATTTAGAGGTCGTAA', 'GCTGCGTTCTTCATCGATGC',
            'GCTGCGTTCTTCATCGATGG', 'GCTACGTTCTTCATCGATGC', 'GCTGCGTTCTTCATCGATGT',
            'ACTGTGTTCTTCATCGATGT', 'GCTGCGTTCTTCATCGTTGC', 'GCGTTCTTCATCGATGC']
